services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres17
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    command: >
      postgres
      -c shared_buffers=1536MB
      -c effective_cache_size=4608MB
      -c work_mem=64MB
      -c maintenance_work_mem=512MB
      -c max_worker_processes=2
      -c max_parallel_workers=2
      -c max_parallel_workers_per_gather=1
      -c random_page_cost=1.0
      -c effective_io_concurrency=400
      -c wal_buffers=32MB
      -c checkpoint_completion_target=0.9
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_connections=100
      -c log_min_duration_statement=1000
      -c log_timezone=America/Sao_Paulo
      -c timezone=America/Sao_Paulo
      -c listen_addresses=*
      -c hba_file=/etc/postgresql/pg_hba.conf

    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 6G
        reservations:
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - pg_net
      - coolify

networks:
  pg_net:
    driver: bridge
  coolify:
    external: true
