services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres17
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 6G
        reservations:
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - pg_net

networks:
  pg_net:
    driver: bridge