# TYPE  DATABASE  USER  ADDRESS             METHOD
local   all       all                       trust
host    all       all   127.0.0.1/32        md5
host    all       all   100.64.10.11/32     md5
host    all       all   100.64.10.12/32     md5
