# TYPE  DATABASE  USER  ADDRESS             METHOD
local   all       all                       trust
host    all       all   127.0.0.1/32        md5
host    all       all   100.100.10.10/32    md5
host    all       all   100.100.10.1/32     md5