shared_buffers = 1GB
effective_cache_size = 2560MB
work_mem = 32MB
maintenance_work_mem = 256MB
max_worker_processes = 2
max_parallel_workers = 2
max_parallel_workers_per_gather = 1
random_page_cost = 1.1
effective_io_concurrency = 200
wal_buffers = 16MB
checkpoint_completion_target = 0.9
min_wal_size = 512MB
max_wal_size = 2GB
max_connections = 100
log_min_duration_statement = 1000
log_timezone = 'America/Sao_Paulo'
timezone = 'America/Sao_Paulo'
listen_addresses = '*'